version: '3.8'
services:
  # service:
  #   build:
  #     context: .
  #     args:
  #       NODE_ENV: 'development'
  #   container_name: service
  #   hostname: service
  #   ports:
  #     - 4000:4000
  #   networks:
  #     - app-net
  #   volumes:
  #     - ./src/:/app/src/
  #     - .env/:/app/.env
  #   restart: unless-stopped
  nginx:
    build:
      dockerfile: Dockerfile
      context: ./nginx
    ports:
      - '81:81'
    networks:
      - app-net
    # volumes:
    #   - ./nginx/nginx.conf:/etc/nginx/nginx.conf
networks:
  app-net:
    driver: bridge
